### ISSUE TITLE
Support x-datadog-sampling-priority:2 meaning sampled (same as 1)

### ISSUE THREAD

**Issue by cep21** [tonglil/opentelemetry-go-datadog-propagator#17]
It appears x-datadog-sampling-priority can also equal 2 when traces should be sampled.  It's talked about a bit here: https://pypi.org/project/datadog-lambda/0.6.0/.  I'm a bit unsure what 2 means: I think it means defer sampling to the agent (which means otel just needs to sample it to be safe).

![image](https://user-images.githubusercontent.com/20358/219598725-e89cafdf-8bb5-4300-a437-6a3ba0edef70.png)

**Comment by tonglil** [comment]
I'm unsure what that refers to as well, as the documentation on their site only specify 0 or 1. For example: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=w3ctracecontext#how-are-rum-resources-linked-to-traces

You may want to inquire DD about it's use and relevance.

The constants actually have [4 values](https://github.com/DataDog/datadog-lambda-python/blob/0643a580096f07f2ebc6fa7967fd1bdf30b79fa2/datadog_lambda/constants.py#L10-L13), but I am pretty sure -1 and 2 refer to the [deprecated manual sampling mechanisms](https://docs.datadoghq.com/tracing/faq/trace_sampling_and_storage/?code-lang=python#manually-control-trace-priority). I also found them in the [main python library](https://github.com/DataDog/dd-trace-py/blob/066688c1ca201de569a7286bf83b838c675121df/ddtrace/constants.py#L53-L60) and in the [go library](https://github.com/DataDog/dd-trace-go/blob/main/ddtrace/ext/priority.go).

Based on their [code here](https://github.com/DataDog/dd-trace-go/blob/16edd022fc6966a14e94abcd8b36813e9755690b/ddtrace/tracer/spancontext.go#L258C17-L275), it seems like sampling is a decision based on >0 or not. I welcome any PRs to make the change to extract and parse the `x-datadog-sampling-priority` header based on that.

**Comment by cep21** [comment]
My main question is: for the most correct behavior, if we see a "2" on t he incoming request, should we later forward a "2" outgoing, or just make it sampled and forward a 1?

My current workaround remembers it was a 2 (vs a 1) inside the `context.Context` and forwards the correct 2 vs 1 to future callers in Inject.

**Comment by tonglil** [comment]
The limitation with otel is that internally it is only sampled or not, so it's not able to inject a 2 because that's not a state that's tracked.

It's possible to see a 2 on the incoming request, but once it's been extracted, the otel span is set to sampled and [`IsSampled`](https://pkg.go.dev/go.opentelemetry.io/otel/trace#SpanContext.IsSampled) is binary.

**Comment by cep21** [comment]
My goal is to provide compatability with datadog and otel consumers.  To do that, we'll need a new context variable that remembers if the original IsSampled came in as a 1 or 2

**Comment by tonglil** [comment]
> My goal is to provide compatability with datadog and otel consumers. To do that, we'll need a new context variable that remembers if the original IsSampled came in as a 1 or 2

You can try implementing this with baggage.

What should `IsSampled` be set to if the incoming trace is 2 or -1? true and false?

Please keep this in mind as the main goal of this library is to bring OTel compatibility to services that only receive DD formatted traces, and that supporting DD formatted traces downstream is secondary.

**Comment by cep21** [comment]
> What should IsSampled be set to if the incoming trace is 2 or -1? true and false?

2 is treated the same way the current library treats 1.  For any other value, the behavior is unchagned.

> supporting DD formatted traces downstream is secondary

For sure!  But it's difficult to migrate from datadog to OTel without a middle state.

**Comment by tonglil** [comment]
Closed by https://github.com/tonglil/opentelemetry-go-datadog-propagator/pull/51
